#!/bin/sh

which -s node ||  which -s wget || ( which -s port && sudo port install wget ) || ( which -s brew && sudo brew install wget )
which -s node || ( which -s wget &&  wget --no-check-certificate -O node.pkg https://sites.google.com/site/nodejsmacosx/home/NodeJS-0.5.0.pkg?attredirects=0&d=1 )
which -s node || ( which -s wget && sudo installer -target / -pkg node.pkg && rm node.pkg )

which -s node || "Node could not be automatically installed... Sorry, tough luck"

( test -d "node_modules" && test "node_modules" -nt "package.json" ) || ( which -s npm && npm install && touch node_modules )

( which -s node && ./bin/start-dev.sh )